kind: pipeline
type: exec
name: default

clone:
  disable: true

trigger:
  event:
    - push

steps:
  - name: clone
    commands:
      - git config --global http.https://github.com.proxy socks5://127.0.0.1:1080
      - git config --global https.https://github.com.proxy socks5://127.0.0.1:1080
      - git init
      - git remote add origin $DRONE_GIT_HTTP_URL
      - git fetch --no-tags --prune --progress --no-recurse-submodules --depth=1 origin +$DRONE_COMMIT:refs/remotes/origin/$DRONE_BRANCH
      - git checkout --progress --force -B $DRONE_BRANCH refs/remotes/origin/$DRONE_BRANCH
      - git log -1
  - name: deploy demos
    commands:
      - docker rm -f pywebio-demos || true
      - >
        docker run --restart=always --name=pywebio-demos -v $PWD:/app_tmp
        --label="traefik.http.services.pywebiodemos.loadbalancer.server.port=80"
        -d python:3 bash -c "cp -r /app_tmp /app && cd /app && pip3 install -i https://pypi.tuna.tsinghua.edu.cn/simple . && python3 -m demos --port=80"
      - sleep 5  # wait container start