name: Sync with mirror repo
on: push
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Push
        run: |
          git fetch --unshallow origin
          git remote add aliyun "https://code.aliyun.com/wang0618/pywebio.git"
          git config credential.helper '!f() { sleep 1; echo "username=${ALIYUN_GIT_USER}"; echo "password=${ALIYUN_GIT_PASSWORD}"; }; f'
          git push -f -u aliyun --tags
        env:
          ALIYUN_GIT_USER: ${{ secrets.ALIYUN_GIT_USER }}
          ALIYUN_GIT_PASSWORD: ${{ secrets.ALIYUN_GIT_PASSWORD }}