name: Tests and Sync
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install JS deps
        run: npm install -D @percy/agent
      - name: Install package
        run: pip3 install -e ".[all]"
      - name: Install dev dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Percy Test
        uses: percy/exec-action@v0.2.0
        with:
          working-directory: ./test
          command: "./run_all.sh"
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
      - name: Upload test output
        uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: test output
          path: test/output
      - name: Upload Codecov Report
        working-directory: ./test
        run: bash <(curl -s https://codecov.io/bash)
  sync:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Push
        run: |
          git fetch --unshallow origin
          git remote add aliyun "https://code.aliyun.com/wang0618/pywebio.git"
          git config credential.helper '!f() { sleep 1; echo "username=${ALIYUN_GIT_USER}"; echo "password=${ALIYUN_GIT_PASSWORD}"; }; f'
          git push -f -u aliyun
        env:
          ALIYUN_GIT_USER: ${{ secrets.ALIYUN_GIT_USER }}
          ALIYUN_GIT_PASSWORD: ${{ secrets.ALIYUN_GIT_PASSWORD }}